window.MRS_PRODUCTS = [
  {id:'saree-01', name:'Samantha Saree', category:'Samantha Saree', price:420, stock:12, badge:'Signature', material:'Silk blend', colors:'Ruby / Antique Gold', images:['assets/products/pink.jpeg','assets/products/green.png','assets/editorial/grey.jpeg'], description:'An occasion-ready drape with a rich, jewel-toned story and a softly luminous finish.'},
  {id:'saree-02', name:'Ivory Petal Saree', category:'Sarees', price:4290, stock:8, badge:'New', material:'Organza', colors:'Ivory / Blush', images:['assets/products/demo-02.svg','assets/products/demo-05.svg','assets/editorial/sarees.svg'], description:'A quiet luxury saree designed around a light, fluid silhouette and delicate border detailing.'},
  {id:'kurti-01', name:'Rose Garden Kurti', category:'Kurtis', price:2190, stock:17, badge:'Best Seller', material:'Cotton silk', colors:'Rose / Cream', images:['assets/products/demo-03.svg','assets/products/demo-06.svg','assets/editorial/kurtis.svg'], description:'A polished everyday kurti with a feminine palette, clean fall and soft-touch texture.'},
  {id:'kurti-02', name:'Maroon Muse Kurti', category:'Kurtis', price:2390, stock:6, badge:'Limited', material:'Viscose', colors:'Maroon / Sand', images:['assets/products/demo-04.svg','assets/products/demo-09.svg','assets/editorial/kurtis.svg'], description:'A modern maroon silhouette with understated detailing for dinners, gatherings and festive days.'},
  {id:'dress-01', name:'Ruby Evening Dress', category:'Dresses', price:3590, stock:9, badge:"Editor's Pick", material:'Crepe', colors:'Ruby / Wine', images:['assets/products/demo-09.svg','assets/products/demo-12.svg','assets/editorial/dresses.svg'], description:'Sculpted but effortless, with a clean neckline and movement designed for evening occasions.'},
  {id:'dress-02', name:'Blush Day Dress', category:'Dresses', price:2990, stock:15, badge:'New', material:'Chiffon', colors:'Blush / Nude', images:['assets/products/demo-14.svg','assets/products/demo-07.svg','assets/editorial/dresses.svg'], description:'A romantic day dress with airy proportions and a subtle tonal story.'},
  {id:'top-01', name:'Pearl Line Top', category:'Tops', price:1690, stock:21, badge:'Everyday', material:'Rayon', colors:'Pearl / Rose', images:['assets/products/demo-05.svg','assets/products/demo-11.svg','assets/editorial/tops.svg'], description:'Minimal, feminine and easy to pair, finished with fine line accents.'},
  {id:'top-02', name:'Wine Edit Top', category:'Tops', price:1790, stock:10, badge:'New', material:'Crepe', colors:'Wine / Ivory', images:['assets/products/demo-12.svg','assets/products/demo-04.svg','assets/editorial/tops.svg'], description:'A confident evening top balancing deep colour with a refined silhouette.'},
  {id:'coord-01', name:'Heritage Co-ord', category:'Co-ord Sets', price:3290, stock:13, badge:'Signature', material:'Cotton satin', colors:'Olive / Cream', images:['assets/products/demo-10.svg','assets/products/demo-15.svg','assets/editorial/coords.svg'], description:'A contemporary two-piece set inspired by classic Indian colour stories.'},
  {id:'coord-02', name:'Golden Hour Co-ord', category:'Co-ord Sets', price:3490, stock:7, badge:'Limited', material:'Satin blend', colors:'Champagne / Gold', images:['assets/products/demo-06.svg','assets/products/demo-13.svg','assets/editorial/coords.svg'], description:'A softly luminous set designed for elevated dinners and celebrations.'},
  {id:'blouse-01', name:'Classic Pearl Blouse', category:'Blouses', price:1890, stock:14, badge:'Core Edit', material:'Silk blend', colors:'Pearl / Gold', images:['assets/products/demo-11.svg','assets/products/demo-15.svg','assets/editorial/blouses.svg'], description:'A versatile blouse designed to sit beautifully with festive and classic sarees.'},
  {id:'blouse-02', name:'Ruby Embellished Blouse', category:'Blouses', price:2490, stock:5, badge:'Limited', material:'Silk', colors:'Ruby / Gold', images:['assets/products/demo-04.svg','assets/products/demo-09.svg','assets/editorial/blouses.svg'], description:'A statement blouse with evening-ready colour and subtle ornamental detailing.'},
  {id:'jewel-01', name:'Luna Drop Earrings', category:'Jewellery', price:990, stock:28, badge:'New', material:'Gold-tone alloy', colors:'Antique Gold', images:['assets/products/demo-13.svg','assets/editorial/jewellery.svg'], description:'Light-catching drop earrings that add a polished finish without overpowering the look.'},
  {id:'jewel-02', name:'Temple Glow Necklace', category:'Jewellery', price:1490, stock:11, badge:'Statement', material:'Gold-tone alloy', colors:'Antique Gold / Ruby', images:['assets/products/demo-01.svg','assets/editorial/jewellery.svg'], description:'A heritage-inspired necklace built for festive dressing and layered styling.'},
  {id:'acc-01', name:'Silk Touch Potli', category:'Accessories', price:1190, stock:18, badge:'Gift Edit', material:'Satin', colors:'Rose / Gold', images:['assets/products/demo-14.svg','assets/editorial/accessories.svg'], description:'A compact potli for occasions, gifting and finishing an evening look.'},
  {id:'acc-02', name:'Everyday Grace Handbag', category:'Accessories', price:1990, stock:9, badge:'New', material:'Vegan leather', colors:'Mocha / Gold', images:['assets/products/demo-16.svg','assets/editorial/accessories.svg'], description:'A structured everyday bag with a soft neutral palette and refined hardware.'}
];
